# copy this file and then dont push it again, add it to git ignore
# (by going into .gitignore and typing db.properties)
# also if you have mysql installed
# and want this to run then use this command when you login as root:

#CREATE USER 'iposca_app'@'localhost' IDENTIFIED BY 'choose_a_password';
#GRANT ALL PRIVILEGES ON ipos_ca.* TO 'iposca_app'@'localhost';
#FLUSH PRIVILEGES;

db.url=jdbc:mysql://localhost:3306/ipos_ca
db.user=iposca_app
db.password=iposcapassword